### ISSUE TITLE
Update Node from 10 to 12

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/fetch-api-data-action#186]
**Describe the bug**

Right now the `.nvmrc` file points to Node 10. This is two versions out of date and should be updated to use the latest Node version. 

**Additional Comments**

* Change the node version, install with `nvm use`.
* Run the usual commands, `yarn install, yarn format, yarn lint, yarn test`. Ensure there are no issues.
* Make applicable readme and fixes to ensure it's clear to the user that this action runs on Node 12+.

**Comment by saravananselvamohan** [comment]
@JamesIves . Would like to work on this issue

**Comment by JamesIves** [comment]
Go for it! I've assigned it to you.

**Comment by saravananselvamohan** [comment]
After the suggested changes., 

- No issues with yarn test
- Fixed issues with yarn lint
- yarn format have few errors. @JamesIves . Need you suggestion how to resolve this.

![yarn format](https://user-images.githubusercontent.com/43172875/94934827-dd341080-04e9-11eb-8634-778c1479c7e7.png)

**Comment by JamesIves** [comment]
Are you using Mac/Linux or Windows?

**Comment by saravananselvamohan** [comment]
Windows 10 with Node version 12.8.4

**Comment by JamesIves** [comment]
This is probably due to the use of single quotes in the format command. Try wrapping the pattern in the format command with double quotes instead?

I'm not a Windows user personally so I'm unsure.

**Comment by saravananselvamohan** [comment]
> This is probably due to the use of single quotes in the format command. Try wrapping the pattern in the format command with double quotes instead?
> 
> I'm not a Windows user personally so I'm unsure.

Thanks @JamesIves . The suggestion you gave worked out. Raised the PR, would like to review

**Comment by JamesIves** [comment]
Approved/merged. Thanks for doing that!
