### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by jasonkarns** [JamesIves/fetch-api-data-action#61]
(Just sharing a tidbit as I've stumbled on this repo through the bug discussion on setup-node action)

I see you have an npm "build" script. That should very most likely be "prepare". (Assuming that script is essentially a compilation step that should occur before publishing.)

That would also simplify your workflow because "prepare" runs automatically after npm-install.

https://docs.npmjs.com/misc/scripts#prepublish-and-prepare

**Comment by JamesIves** [comment]
Appreciate the tip, thanks! I'll implement these changes in a future update.
