### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by davideduma** [JamesIves/fetch-api-data-action#860]
## Describe the bug

I do send a huge message of 350.000 characters in the body.
So I get the next issue:

![image](https://user-images.githubusercontent.com/86481341/223477644-9640c928-ae87-456b-a646-d682efebdc09.png)

## Reproduction Steps

send a huge message of 350.000 characters in the body.

## Logs

![image](https://user-images.githubusercontent.com/86481341/223477644-9640c928-ae87-456b-a646-d682efebdc09.png)

## Workflow

![image](https://user-images.githubusercontent.com/86481341/223478269-67187099-bf71-4b35-9642-63cb3f88794a.png)

**Comment by JamesIves** [comment]
Try setting set-output to false and it should circumvent the issue. There is a limit with the action runners that cause an overflow here.
